// Code generated by protoc-gen-go. DO NOT EDIT.
// This is a stub file - in production, run: protoc --go_out=. --go-grpc_out=. proto/task/v1/task.proto

package taskv1

// This file will be generated from task.proto
// For now, we'll implement the service directly in main.go without generated code
